version: "3.1"
services:
  poracle_db:
    image: postgres:latest
    ports: 
      - 5432:5432
    expose:
      - 5432
    environment: 
      POSTGRES_DB: poracle_database
      POSTGRES_USER: poracle_user
      POSTGRES_PASSWORD: poracle_secure_database_password
  poracle:
    build: 
      context: .
    ports:
      - "3030:3030"
    depends_on: 
      - nominatim
      - poracle_db
    environment: 
      PORACLE_SERVER_HOST: 0.0.0.0
      PORACLE_DB_TYPE: pg
      GEOCODING_PROVIDER_URL: nominatim:8080
      PORACLE_DB_HOST: poracle_db
      PORACLE_DB_DATABASE: poracle_database
      PORACLE_DB_USER: poracle_user
      PORACLE_DB_PASSWORD: poracle_secure_database_password
      PORACLE_DB_PORT: 5432
  nominatim:
    ports:
      - "7070:8080"
    volumes: 
      - ./nominatimData/:/data/
    build:
      context: https://github.com/PoracleJS/poracle-nominatim.git
    depends_on: 
      - nominatim_db
    environment: 
      NOMINATIM_DB_HOST: nominatim_db
      NOMINATIM_DB_PORT: 6432
      NOMINATIM_DB_USER: nominatim_user
      NOMINATIM_DB_PASSWORD: nominatim_secure_database_password
      NOMINATIM_DB_NAME: nominatim_database
      NOMINATIM_PBF_URL: http://download.geofabrik.de/europe/estonia-latest.osm.pbf
      NOMINATIM_INIT: 'true'
      NOMINATIM_IMPORT_THREADS: 4
  nominatim_db:
    image: postgres:latest
    ports: 
      - 6432:5432
    expose:
      - 5432
    environment: 
      POSTGRES_DB: nominatim_database
      POSTGRES_USER: nominatim_user
      POSTGRES_PASSWORD: nominatim_secure_database_password
    volumes:
      - ./nominatimData/postgres:/var/lib/postgresql/12/main  